version: '3.8'

services:
    db:
      image: postgres:13-alpine3.17
      environment:
        POSTGRES_DB: coffee_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12341234
      ports:
        - "5432:5432"
      volumes:
        - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - app-network
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5

    tomcat:
      image: tomcat:latest
      volumes:
        - ./build/libs/coffee-shop.war:/usr/local/tomcat/webapps/coffee-shop.war
      ports:
        - "8080:8080"
      depends_on:
        db:
          condition: service_healthy
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

